[build]
  command = "bash ./build-for-netlify.sh"
  publish = "dist/public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "pg-native", "@babel/preset-typescript", "lightningcss", "vite", "@vitejs/plugin-react", "@replit/vite-plugin-shadcn-theme-json", "@replit/vite-plugin-runtime-error-modal", "@replit/vite-plugin-cartographer"]

[functions."api-standalone"]
  included_files = ["server/**", "shared/**", "client/**", "dist/**"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[dev]
  command = "npm run dev"
  port = 5000

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-standalone/api/:splat"
  status = 200
  force = true

# Explicitly handle some key API endpoints
[[redirects]]
  from = "/api/waitlist"
  to = "/.netlify/functions/api-standalone/api/waitlist"
  status = 200
  force = true

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/api-standalone/api/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200